### ISSUE TITLE
Does the RunSignUp API allow user registration?

### ISSUE THREAD

**Issue by randybaum** [RunSignUp-Team/OpenSource#1]
👋 Hi there!

I'm building a website for a client (Race Producer), and they utilize your RunSignUp platform for registration (among other things). In short, I was hoping you guys might have a way for me to embed their RSU registration forms on the site, or perhaps I could send registration info to RSU via the API, but it would appear as though this is not currently possible.

Is that correct? Or is there another way I could "customize" the registration experience?

Any insight you may have would be greatly appreciated! Thanks!

**Comment by brucekratz** [comment]
Randy
Correct, we do not have an API for the registration process.  The registration process is a complex multi-step wizard with a lot of configuration options, validation, fraud prevention and PCI certified credit card processing and we want to ensure it is high performing and with high usability.

The best way for your customer to "customize" that experience is by using our extensive set of options to customize their race.  Of course they can link from their website to their Registration process - and they can also use their domain (or subdomain) instead of the standard RunSignup domain in the URL.

**Comment by randybaum** [comment]
@brucekratz Thanks for the speedy response! I kinda figured this much, and certainly appreciate the complexities involved in everything you've built. I'll check the RSU docs again, and see what kinda fun stuff we can do with the "built-in" website you guys provide. Thanks for your help!

**Comment by brucekratz** [comment]
While you research what our built-in website capabilities are keep this in mind.  

1) The registration process is controlled more by what the race configuration is - and options you can set in the Director's Dashboard.  The "built-in website" capability is a full website dedicated to your event with lots of options.

2) We are currently moving to a completely new "point and click" website builder that will be superior than what we currently have available in Race Websites.   We are rolling this new capability out in phases.  Since Race websites have lots of options today, the new website builder is not available for Races.  But if you want to check out how it is coming along skim through this video:  https://youtu.be/Coc3MWwZ9bc 
And you can create an Organizational Website today - which may actually be what you are looking for.
