### ISSUE TITLE
Advanced Search results in past events being displayed

### ISSUE THREAD

**Issue by PhillyWebGuy** [RunSignUp-Team/OpenSource#2]
This has been a bug for well over a year and it is odd that no one has fixed this yet. 

![image](https://github.com/RunSignUp-Team/OpenSource/assets/449963/6055e047-f2b5-4a6c-bd54-6fe94078530b)

Pretty much every time I use the site, I will perform an advanced search to see what is coming up, and there are always many races that have already happened. I always see items that also appear to be test data too. 

![image](https://github.com/RunSignUp-Team/OpenSource/assets/449963/c60bb20b-51e7-4592-a3a1-05b4a62788f3)

**Comment by brucekratz** [comment]
Hi.  Many event organizers want to try out our platform features with a test race.  They have an option to mark it as Draft so that it does not show up in search results.  However, since our platform is free and open to the public, we cannot always control how event organizers are using the test mode (or not using it).  Thanks for your feedback.

**Comment by runsignup** [comment]
The reason these events show is that they happen over a long range of dates, and we show races that are currently open. with event opening date being listed first.  Not sure there is a great solution for eliminating those that you do not want to see.  Thanks for the suggestion Ed.
